# Generated by Django 6.0.2 on 2026-02-25 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('udid', models.CharField(max_length=100, unique=True, verbose_name='设备唯一标识')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='设备型号')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='操作系统版本')),
                ('battery_level', models.IntegerField(default=0, verbose_name='电池电量 (%)')),
                ('battery_health', models.CharField(blank=True, max_length=50, verbose_name='电池健康状态')),
                ('memory_usage', models.IntegerField(default=0, verbose_name='内存使用率 (%)')),
                ('storage_used', models.FloatField(default=0, verbose_name='已用存储 (GB)')),
                ('storage_total', models.FloatField(default=0, verbose_name='总存储 (GB)')),
                ('network_status', models.CharField(blank=True, max_length=50, verbose_name='网络状态')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最后在线时间')),
                ('background_app_refresh_enabled', models.BooleanField(default=True, verbose_name='启用后台应用刷新')),
                ('background_activity_restricted', models.BooleanField(default=False, verbose_name='限制后台活动')),
                ('low_power_mode', models.BooleanField(default=False, verbose_name='低电量模式')),
                ('enrolled', models.BooleanField(default=False, verbose_name='已注册MDM')),
                ('enrollment_date', models.DateTimeField(blank=True, null=True, verbose_name='注册日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.IntegerField()),
                ('memory_usage', models.IntegerField()),
                ('storage_used', models.FloatField()),
                ('network_status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='devices.device')),
            ],
            options={
                'verbose_name': '设备状态历史',
                'verbose_name_plural': '设备状态历史',
                'ordering': ['-timestamp'],
            },
        ),
    ]
