# Generated by Django 6.0.2 on 2026-02-25 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='策略名称')),
                ('policy_type', models.CharField(choices=[('background_refresh', '后台应用刷新'), ('background_activity', '后台活动限制'), ('power_saving', '省电模式'), ('network_restriction', '网络限制'), ('app_management', '应用管理')], max_length=50, verbose_name='策略类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('configuration', models.JSONField(default=dict, verbose_name='配置参数')),
                ('apply_to_all', models.BooleanField(default=False, verbose_name='应用到所有设备')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('schedule_start', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('schedule_end', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='policies', to='devices.device', verbose_name='应用设备')),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '策略',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_history', to='devices.device')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='policies.policy')),
            ],
            options={
                'verbose_name': '策略应用历史',
                'verbose_name_plural': '策略应用历史',
                'ordering': ['-applied_at'],
            },
        ),
    ]
